In [6]:
def luas_p(alas,tinggi):
    luas=alas * tinggi
    print(luas)

luas_p(5,4)

20


In [39]:
def change(mylist):
    mylist=[1,2,3,4]
    print(mylist)
    

change(1)

[1, 2, 3, 4]


In [40]:
def change():
    mylist=[1,2,3,4]
    print(mylist)
    

change()

[1, 2, 3, 4]


In [28]:
def panggil(x):
    y = 10
    z = x + y
    return z

panggil(23)


33

In [47]:
import person

print(person.name)
print(person.devices)

person.display("antm")

zack
['laptop', 'smartphone', 'tablet']
arg = antm


In [48]:
!pip install pandas

In [2]:
import pandas as np

In [50]:
!pip install numpy

In [13]:
import numpy as np

arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [10]:
arr.ndim

1

In [5]:
matriks=arr.reshape(3,2)
print(matriks)

[[0 1]
 [2 3]
 [4 5]]


In [8]:
arr.ndim

1

In [7]:
arr.shape

(6,)

#SOal


In [15]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [16]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [18]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[0,2])

7


In [26]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[2,2:4])

[11 12]


In [39]:
arr=np.array([[1,2,3,4,8,10],[5,6,7,8,7,10],[9,10,11,12,11,12]])
print(arr[arr>=3])

[ 3  4  8 10  5  6  7  8  7 10  9 10 11 12 11 12]
